version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_test
    ports:
      - 5433:5432
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  postgres-test-data:
