version: "3.8"
services:
  blog:
    image: geisonbiazus/blog:50
    restart: always
    environment:
      VIRTUAL_HOST: blog.geisonbiazus.com
      LETSENCRYPT_HOST: blog.geisonbiazus.com
      BASE_URL: https://blog.geisonbiazus.com
    ports:
      - 5000:3000
