version: "3.8"
services:
  blog:
    image: geisonbiazus/blog:35
    restart: always
    environment:
      VIRTUAL_HOST: blog.geisonbiazus.com
      LETSENCRYPT_HOST: blog.geisonbiazus.com
    ports:
      - 5000:3000
