name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "deployment/**"
      - "./README/md"
  pull_request:
    paths-ignore:
      - "deployment/**"
      - "./README/md"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: golang:1.18.1-alpine

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_TEST_URL: postgres://postgres:postgres@postgres:5432/blog_test?sslmode=disable

    steps:
      - uses: actions/checkout@v2

      - name: Install build deps
        run: apk add build-base

      - name: Install migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrations
        run: make db_migrate db_url=$POSTGRES_TEST_URL

      - name: Run tests
        run: make test

  deploy:
    name: Deploy to Heroku
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-geisonbiazus"
          heroku_email: "geisonbiazus@gmail.com"
          usedocker: true
