name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployment/**'
      - './README/md'
  pull_request:
    paths-ignore:
      - 'deployment/**'
      - './README/md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: golang:1.16.3-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install build deps
        run: apk add build-base

      - name: Run tests
        run: go test ./...

  build_and_push_image:
    name: Build and push Docker image
    needs: test
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            geisonbiazus/blog:latest
            geisonbiazus/blog:${{ github.run_number }}
  
  update_docker_compose:
    name: Update docker-compose
    needs: build_and_push_image
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update docker-compose file
        run: "sed -i -e 's|image: geisonbiazus/blog:.*|image: geisonbiazus/blog:${{ github.run_number }}|'  deployment/docker-compose/docker-compose.yml"

      - name: Commit changes
        run: |
          echo "${{ github.ref }}"
          git config --global user.name 'Geison Biazus'
          git config --global user.email 'geisonbiazus@gmail.com'
          git commit -am "Update docker-compose image version to ${{ github.run_number }}"
          git push

          