name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: golang:1.16.3-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install build deps
        run: apk add build-base

      - name: Run tests
        run: go test ./...
